from  . import inline_sura1
from  . import inline_sura8
from . import inline_sura9
from . import inline_sura10
from . import inline_sura11
from . import inline_sura12
from . import inline_sura13
from . import inline_sura14
from . import inline_sura15
from . import inline_sura16
from . import inline_sura17
from . import inline_sura18
from . import inline_sura19
from . import inline_sura20
from . import inline_sura21
from . import inline_sura22
from . import inline_sura23
from . import inline_sura24
from . import inline_sura25
from . import inline_sura26
from . import inline_sura27
from . import inline_sura28
from . import inline_sura29
from . import inline_sura30
from . import inline_sura31
from . import inline_sura32
from . import inline_sura33
from . import inline_sura34
from . import inline_sura35
from . import inline_sura36
from . import inline_sura37
from . import inline_sura38
from . import inline_sura39
from . import inline_sura40
from . import inline_sura41
from . import inline_sura42
from . import inline_sura43
from . import inline_sura44
from . import inline_sura45
from . import inline_sura46
from . import inline_sura47
from . import inline_sura48
from . import inline_sura49
from . import inline_sura50
from . import inline_sura51
from . import inline_sura52
from . import inline_sura53
from . import inline_sura54
from . import inline_sura55
from . import inline_sura56
from . import inline_sura57
from . import inline_sura58
from . import inline_sura59
from . import inline_sura60
from . import inline_sura61
from . import inline_sura62
from . import inline_sura63
from . import inline_sura64
from . import inline_sura65
from . import inline_sura66
from . import inline_sura67
from . import inline_sura68
from . import inline_sura69
from . import inline_sura70
from . import inline_sura71
from . import inline_sura72
from . import inline_sura73
from . import inline_sura74
from . import inline_sura75
from . import inline_sura76
from . import inline_sura77
from . import inline_sura78
from . import inline_sura79
from . import inline_sura80
from . import inline_sura81
from . import inline_sura82
from . import inline_sura83
from . import inline_sura84
from . import inline_sura85
from . import inline_sura86
from . import inline_sura87
from . import inline_sura88
from . import inline_sura89
from . import inline_sura90
from . import inline_sura91
from . import inline_sura92
from . import inline_sura93
from . import inline_sura94
from . import inline_sura95
from . import inline_sura96
from . import inline_sura97
from . import inline_sura98
from . import inline_sura99
from . import inline_sura100
from . import inline_sura101
from . import inline_sura102
from . import inline_sura103
from . import inline_sura104
from . import inline_sura105
from . import inline_sura106
from . import inline_sura107
from . import inline_sura108
from . import inline_sura109
from . import inline_sura110
from . import inline_sura111
from . import inline_sura112
from . import barcha_suralar
from . import keyingi_bolim
from . import keyingi_inline_buttons