from . import help
from . import start
from . import Quron
from . import asosiym
from . import malumotnoma
from . import dasturchi
from . import turlinashida
from . import uznashid
from . import al_afasiy
from . import al_balashu
from . import al_dossari
from . import ash_shatri
from . import arabcha_nashids
from . import turkcha_nashids
from . import chechencha_nashids
from . import falastin_nashids
from . import tojik_nashids
from . import pokiston_nasheeds
from . import ramazon_nashids
from . import aralash_nashids
from . import hurrun_nashids
from . import kuchli_nashids
from . import yangi_nashids
from . import gozal_azonlar
from . import biz_haqimizda
from . import murojaat
from . import echo